#-Automagically created from GeoTools-
#Tue Feb 03 11:01:17 CET 2026
TimeAttribute=ingestion
ExpandToRGB=false
TypeName=timeseries_data
SuggestedFormat=org.geotools.gce.geotiff.GeoTiffFormat
Name=timeseries_data
SuggestedSPI=it.geosolutions.imageioimpl.plugins.tiff.TIFFImageReaderSpi
LevelsNum=1
PathType=RELATIVE
Heterogeneous=false
Caching=false
HeterogeneousCRS=false
LocationAttribute=location
Levels=0.002245788210298804,0.002245788210298804
CheckAuxiliaryMetadata=false
MosaicCRS=EPSG\:4326
ElevationAttribute=elevation
